package com.eer_system.model;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.device_name
     *
     * @mbggenerated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.userID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.use_postion
     *
     * @mbggenerated
     */
    private String usePostion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.appo_day
     *
     * @mbggenerated
     */
    private Date appoDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.appo_time
     *
     * @mbggenerated
     */
    private String appoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.creation_date
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.valid
     *
     * @mbggenerated
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.device_id
     *
     * @return the value of log.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.device_id
     *
     * @param deviceId the value for log.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.device_name
     *
     * @return the value of log.device_name
     *
     * @mbggenerated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.device_name
     *
     * @param deviceName the value for log.device_name
     *
     * @mbggenerated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.userID
     *
     * @return the value of log.userID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.userID
     *
     * @param userid the value for log.userID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_name
     *
     * @return the value of log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_name
     *
     * @param userName the value for log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.use_postion
     *
     * @return the value of log.use_postion
     *
     * @mbggenerated
     */
    public String getUsePostion() {
        return usePostion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.use_postion
     *
     * @param usePostion the value for log.use_postion
     *
     * @mbggenerated
     */
    public void setUsePostion(String usePostion) {
        this.usePostion = usePostion == null ? null : usePostion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.appo_day
     *
     * @return the value of log.appo_day
     *
     * @mbggenerated
     */
    public Date getAppoDay() {
        return appoDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.appo_day
     *
     * @param appoDay the value for log.appo_day
     *
     * @mbggenerated
     */
    public void setAppoDay(Date appoDay) {
        this.appoDay = appoDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.appo_time
     *
     * @return the value of log.appo_time
     *
     * @mbggenerated
     */
    public String getAppoTime() {
        return appoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.appo_time
     *
     * @param appoTime the value for log.appo_time
     *
     * @mbggenerated
     */
    public void setAppoTime(String appoTime) {
        this.appoTime = appoTime == null ? null : appoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.creation_date
     *
     * @return the value of log.creation_date
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.creation_date
     *
     * @param creationDate the value for log.creation_date
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.valid
     *
     * @return the value of log.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.valid
     *
     * @param valid the value for log.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}